name: pandoc-crossref
version: '0.3.17.1'
synopsis: Pandoc filter for cross-references
description: pandoc-crossref is a pandoc filter for numbering figures, equations,
  tables and cross-references to them.
category: Text
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
license: GPL-2
license-file: LICENSE
github: lierdakil/pandoc-crossref
extra-source-files:
- test/*.inc
- CHANGELOG.md
- licenses/LICENSE.roman-numerals
data-files:
- docs/demo/demo.md
- docs/index.md
- test/m2m/*/*
dependencies:
  base: ">=4.11 && <5"
  text: ">=1.2.2 && <2.2"
  pandoc: ">=3.1.8 && < 3.5"
  pandoc-types: ">= 1.23 && < 1.24"
_deps:
  containers: &containers { containers: ">=0.1 && <0.7" }
  criterion: &criterion { criterion: ">=1.5.9.0 && <1.7" }
  data-default: &data-default { data-default: ">=0.4 && <0.8" }
  deepseq: &deepseq { deepseq: ">= 1.4 && < 1.6" }
  directory: &directory { directory: ">=1 && <1.4" }
  filepath: &filepath { filepath: ">=1.1 && <1.6" }
  gitrev: &gitrev { gitrev: ">= 1.3.1 && < 1.4" }
  hspec: &hspec { hspec: ">=2.4.4 && <3" }
  microlens-ghc: &microlens-ghc { microlens-ghc: ">=0.4.3.10 && < 0.5.0.0" }
  microlens-mtl: &microlens-mtl { microlens-mtl: ">=0.2.0.1 && <0.3.0.0" }
  microlens-th: &microlens-th { microlens-th: ">=0.4.3.10 && < 0.5.0.0" }
  microlens: &microlens { microlens: ">=0.4.12.0 && <0.5.0.0" }
  mtl: &mtl { mtl: ">=1.1 && <2.4" }
  open-browser: &open-browser { open-browser: ">= 0.2 && < 0.3" }
  optparse-applicative: &optparse-applicative { optparse-applicative: ">= 0.13 && < 0.19" }
  syb: &syb { syb: ">=0.4 && <0.8" }
  template-haskell: &template-haskell { template-haskell: ">=2.7.0.0 && <3.0.0.0" }
  temporary: &temporary { temporary: ">= 1.2 && < 1.4" }
  utility-ht: &utility-ht { utility-ht: ">=0.0.11 && <0.1.0" }
  ##############################################################################
  internal-lib-deps: &internal-lib-deps
    <<: *containers
    <<: *data-default
    <<: *directory
    <<: *filepath
    <<: *microlens
    <<: *microlens-ghc
    <<: *microlens-mtl
    <<: *microlens-th
    <<: *mtl
    <<: *syb
    <<: *template-haskell
    <<: *utility-ht
  lib-deps: &lib-deps
    pandoc-crossref-internal: null
    <<: *mtl
  exec-deps: &exec-deps
    pandoc-crossref: null
    <<: *deepseq
    <<: *gitrev
    <<: *open-browser
    <<: *optparse-applicative
    <<: *template-haskell
    <<: *temporary
  test-deps: &test-deps
    pandoc-crossref: null
    pandoc-crossref-internal: null
    <<: *containers
    <<: *data-default
    <<: *hspec
    <<: *microlens
    <<: *mtl
  test-int-deps: &test-int-deps
    pandoc-crossref: null
    <<: *directory
    <<: *filepath
    <<: *hspec
  bench-deps: &bench-deps
    pandoc-crossref: null
    <<: *criterion
library:
  source-dirs: lib
  ghc-options: -Wall
  exposed-modules:
  - Text.Pandoc.CrossRef
  other-modules: []
  dependencies:
    <<: *lib-deps
internal-libraries:
  pandoc-crossref-internal:
    other-modules: []
    source-dirs: lib-internal
    dependencies:
      <<: *internal-lib-deps
flags:
  enable_flaky_tests:
    description: Some tests rely on specific behaviour of pandoc, which
      may change between minor versions. These are still useful indicators for the
      developer, but not necessarily indicating there's a problem with the
      package itself. Enable if you know what you are doing.
    manual: true
    default: false
executables:
  pandoc-crossref:
    main: pandoc-crossref.hs
    other-modules:
      - ManData
    source-dirs: src
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
      <<: *exec-deps
tests:
  test-pandoc-crossref:
    when:
      - condition: flag(enable_flaky_tests)
        cpp-options: -DFLAKY
    main: test-pandoc-crossref.hs
    other-modules:
      - Native
    generated-other-modules:
      - Paths_pandoc_crossref
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
      <<: *test-deps
  test-integrative:
    when:
      - condition: flag(enable_flaky_tests)
        cpp-options: -DFLAKY
    main: test-integrative.hs
    other-modules: []
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
      <<: *test-int-deps
    build-tools:
    - pandoc-cli:pandoc
benchmarks:
  simple:
    main: bench-simple.hs
    other-modules:
      Native
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
      <<: *bench-deps
