name: pandoc-crossref
version: '0.4.0.0'
synopsis: Pandoc filter for cross-references
description: pandoc-crossref is a pandoc filter for numbering figures, equations,
  tables and cross-references to them.
category: Text
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
license: GPL-2
license-file: LICENSE
github: lierdakil/pandoc-crossref
extra-source-files:
- test/*.inc
- CHANGELOG.md
- settings/*
data-files:
- docs/demo/demo.md
- docs/index.md
- test/m2m/*/*
dependencies:
- base >=4.11 && <5
- pandoc >=2.10 && < 2.14
- pandoc-types >=1.21 && < 1.23
- text >=1.2.2 && <1.3
library:
  source-dirs: lib
  ghc-options: -Wall
  exposed-modules:
  - Text.Pandoc.CrossRef
  dependencies:
    - pandoc-crossref-internal
    - mtl >=1.1 && <2.3
internal-libraries:
  pandoc-crossref-internal:
    ghc-options: -Wall
    source-dirs: lib-internal
    dependencies:
    - mtl >=1.1 && <2.3
    - containers >=0.1 && <0.7
    - data-default >=0.4 && <0.8
    - data-accessor >=0.2.2.6 && <0.3.0.0
    - data-accessor-template >=0.2.1.12 && <0.3.0.0
    - data-accessor-transformers >=0.2.1.6 && <0.3.0.0
    - roman-numerals ==0.5.*
    - syb >=0.4 && <0.8
    - utility-ht >=0.0.11 && <0.1.0
    - directory >=1 && <1.4
    - filepath >=1.1 && <1.5
    - template-haskell >=2.7.0.0 && <3.0.0.0
    - bytestring
flags:
  enable_flaky_tests:
    description: Some tests rely on specific behaviour of pandoc, which
      may change between minor versions. These are still useful indicators for the
      developer, but not necessarily indicating there's a problem with the
      package itself. Enable if you know what you are doing.
    manual: true
    default: false
executables:
  pandoc-crossref:
    main: pandoc-crossref.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - pandoc-crossref
    - optparse-applicative >= 0.13 && < 0.17
    - open-browser >= 0.2 && < 0.3
    - temporary >= 1.2 && < 1.4
    - deepseq >= 1.4 && < 1.5
    - gitrev >= 1.3.1 && < 1.4
    - template-haskell >=2.7.0.0 && <3.0.0.0
tests:
  test-pandoc-crossref:
    when:
      - condition: flag(enable_flaky_tests)
        cpp-options: -DFLAKY
    main: test-pandoc-crossref.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - pandoc-crossref
    - pandoc-crossref-internal
    - hspec >=2.4.4 && <3
    - mtl >=1.1 && <2.3
    - containers >=0.1 && <0.7
    - data-default >=0.4 && <0.8
    - data-accessor >=0.2.2.6 && <0.3.0.0
  test-integrative:
    when:
      - condition: flag(enable_flaky_tests)
        cpp-options: -DFLAKY
    main: test-integrative.hs
    other-modules: []
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - pandoc-crossref
    - hspec >=2.4.4 && <3
    - directory >=1 && <1.4
    - filepath >=1.1 && <1.5
benchmarks:
  simple:
    main: bench-simple.hs
    other-modules:
      Native
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - pandoc-crossref
    - criterion >=1.5.9.0 && <1.6
