flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  $targets: -Werror -optl-fuse-ld=bfd
packages:
- .
allow-newer: false
extra-deps:
- roman-numerals-0.5.1.5
resolver: nightly-2019-03-07
